### ISSUE TITLE
Make the install role log to a file

### ISSUE THREAD

**Issue by mikecharles** [noaa-nws-cpc/app-deployer#28]
The Ansible install role has the following:

```yaml
####################################################################################################
#                                         Install role tasks                                       #
####################################################################################################
---
# Run the install target in the Makefile
- name: make install
  sudo: no
  shell: . ~/.profile && cd {{ deploy_path }}/current && make install
...
```

The `make install` command should log its output to a file so that in long deployments the user can `tail -f` the file to see that things are happening.
